POST http://localhost:3000/register/
Content-Type: application/json
{
    "username": "vikas",
    "password": "vikas@123"
}
###
POST http://localhost:3000/log-in/
Content-Type: application/json
{
    "username": "vikas",
    "password": "vikas@123"
}
###
GET http://localhost:3000/get-events/
